### PR TITLE
Added "Export EPGP Traffic" feature

### PR DESCRIPTION
**Pull request by PseudoDesign**
Added "Export EPGP Traffic" button to EPGP Traffic Window:

image

Added "Export EPGP Traffic" window.  I modeled this window after the "Export Standings" window:

image

image

### CODE REVIEW

**Comment by PseudoDesign** [comment]
Raw data outputs:
CSV:
```target_name,issuer_name,action,ep_before,ep_after,gp_before,gp_after,item,timestamp
Sowwie,Osso,Subtract EP -1 (test reversal),1,0,1,1,,1574507548
Sowwie,Osso,Add EP +1 (test),0,1,1,1,,1574507534```

JSON:
```{"epgp_traffic":[{"target_name":"Sowwie","issuer_name":"Osso","action":"Subtract EP -1 (test reversal)","ep_before":"1","ep_after":"0","gp_before":"1","gp_after":"1","timestamp":"1574507548",},{"target_name":"Sowwie","issuer_name":"Osso","action":"Add EP +1 (test)","ep_before":"0","ep_after":"1","gp_before":"1","gp_after":"1","timestamp":"1574507534",},]}```

**Comment by Gazler** [comment]
Hey, this looks useful. Just a small note, the JSON output by this isn't actually valid due to the training commas.

Here's a (prettifier) diff of the changes to make it validate.

```
{
  "epgp_traffic": [
    {
      "target_name": "Sowwie",
      "issuer_name": "Osso",
      "action": "Subtract EP -1 (test reversal)",
      "ep_before": "1",
      "ep_after": "0",
      "gp_before": "1",
      "gp_after": "1",
      "timestamp": "1574507548", // this one
    },
    {
      "target_name": "Sowwie",
      "issuer_name": "Osso",
      "action": "Add EP +1 (test)",
      "ep_before": "0",
      "ep_after": "1",
      "gp_before": "1",
      "gp_after": "1",
      "timestamp": "1574507534", // this one
    }, // and this one
  ]
}
```

```
{
  "epgp_traffic": [
    {
      "target_name": "Sowwie",
      "issuer_name": "Osso",
      "action": "Subtract EP -1 (test reversal)",
      "ep_before": "1",
      "ep_after": "0",
      "gp_before": "1",
      "gp_after": "1",
      "timestamp": "1574507548"
    },
    {
      "target_name": "Sowwie",
      "issuer_name": "Osso",
      "action": "Add EP +1 (test)",
      "ep_before": "0",
      "ep_after": "1",
      "gp_before": "1",
      "gp_after": "1",
      "timestamp": "1574507534"
    }
  ]
}
```

**Comment by Gazler** [comment]
Would it be possible to include the item id in the export too? I can see it in the traffic, but it isn't present at the point of export.

**Comment by Gazler** [comment]
I just had a quick look into extracting the item id. Looks like there are a couple of options. You can parse the `itemLink` directly:

https://wowwiki.fandom.com/wiki/ItemLink#Details

Or you can use https://wowwiki.fandom.com/wiki/API_GetItemInfo to get the name and https://wow.gamepedia.com/API_GetItemInfoInstant to get the id.

**Comment by Gazler** [comment]
@PseudoDesign I hope you don't mind, I took a stab at fixing the JSON and adding the item ID and opened a PR into your fork. https://github.com/PseudoDesign/CEPGP-Retail/pull/1/files

**Pull request closed without merging**
